# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'kugga-backend'

steps:
  - script: |
#      docker build -f Dockerfile -t $(imageName) .
#      docker images
#      docker login -u $(aliusername) -p $(alipassword) registry.cn-hangzhou.aliyuncs.com
#      docker tag $(imageName):latest registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-backend:latest
#      docker push registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-backend:latest

  - task: SSH@0
    displayName: 'deploy to remote machine'
    inputs:
      sshEndpoint: 'huaweicloud'
      runOptions: inline

      inline: |
        echo '1'
        echo ${DATABASE_HOST}
        echo '2'
        echo $DATABASE_HOST
        ehco '3'
        ehco $(DATABASE_HOST)
#        containers1=$(docker ps -q -a --filter name=kugga-backend)
#        if test -n "$containers1"; then
#         docker rm -f $(docker ps -q -a --filter name=kugga-backend) >> /dev/null 2>&1
#         rc=$?
#         if [[ $rc != 0 ]];
#         then
#           echo 'failed to remove container...'
#           exit $rc;
#         else
#           echo 'success to remove container...'
#         fi
#        fi
#
#        docker pull registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-backend:latest >> /dev/null
#        2>&1
#        rc=$?
#        if [[ $rc != 0 ]];
#        then
#         echo 'failed to pull container...'
#         exit $rc;
#        else
#         echo 'success to pull container...'
#        fi
#
#        docker run -d --name kugga-backend -e DATABASE_HOST=${DATABASE_HOST} -e DATABASE_PORT=${DATABASE_PORT} -e DATABASE_USERNAME=${DATABASE_USERNAME} -e DATABASE_PASSWORD=${DATABASE_PASSWORD} -e REDIS_HOST=${REDIS_HOST}  -e REDIS_PORT=${REDIS_PORT} -e JWT_SECRET_KEY=${JWT_SECRET_KEY} -e OSS_ENDPOINT=${OSS_ENDPOINT} -e ALI_KEY_ID=${ALI_KEY_ID} -e ALI_KEY_SECRET=${ALI_KEY_SECRET} -e BUCKET_NAME=${BUCKET_NAME} -e AVATAR_FOLDER_URL=${AVATAR_FOLDER_URL}  -p 10086:10086 -p 5555:5555 registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-backend:latest >> /dev/null 2>&1
#        rc=$?
#        if [[ $rc != 0 ]];
#        then
#         echo 'failed to run container...'
#         exit $rc;
#        else
#         echo 'success to run container...'
#        fi