package com.ayang818.kugga.services.pojo.model;

public class ChatIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_message_index.chat_message_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    private String chatMessageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_message_index.sender_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    private Long senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_message_index.receiver_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    private Long receiverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_message_index.chat_message_id
     *
     * @return the value of chat_message_index.chat_message_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public String getChatMessageId() {
        return chatMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_message_index.chat_message_id
     *
     * @param chatMessageId the value for chat_message_index.chat_message_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public void setChatMessageId(String chatMessageId) {
        this.chatMessageId = chatMessageId == null ? null : chatMessageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_message_index.sender_id
     *
     * @return the value of chat_message_index.sender_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_message_index.sender_id
     *
     * @param senderId the value for chat_message_index.sender_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_message_index.receiver_id
     *
     * @return the value of chat_message_index.receiver_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_message_index.receiver_id
     *
     * @param receiverId the value for chat_message_index.receiver_id
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }
}