package com.ayang818.kugga.services.pojo.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.uid
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.username
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.password
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.avatar
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.email
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user.is_blocked
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    private Boolean blocked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.uid
     *
     * @return the value of kugga_user.uid
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.uid
     *
     * @param uid the value for kugga_user.uid
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.username
     *
     * @return the value of kugga_user.username
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.username
     *
     * @param username the value for kugga_user.username
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.password
     *
     * @return the value of kugga_user.password
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.password
     *
     * @param password the value for kugga_user.password
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.avatar
     *
     * @return the value of kugga_user.avatar
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.avatar
     *
     * @param avatar the value for kugga_user.avatar
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.email
     *
     * @return the value of kugga_user.email
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.email
     *
     * @param email the value for kugga_user.email
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user.is_blocked
     *
     * @return the value of kugga_user.is_blocked
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user.is_blocked
     *
     * @param blocked the value for kugga_user.is_blocked
     *
     * @mbg.generated Thu Jan 23 15:45:00 CST 2020
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }
}