package com.ayang818.kugga.services.pojo.model;

import java.util.Date;

public class UserRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user_relation.owner_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    private Long ownerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user_relation.other_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    private Long otherUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user_relation.last_mid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    private Long lastMid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user_relation.is_pass
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    private Byte pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kugga_user_relation.create_time
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user_relation.owner_uid
     *
     * @return the value of kugga_user_relation.owner_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public Long getOwnerUid() {
        return ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user_relation.owner_uid
     *
     * @param ownerUid the value for kugga_user_relation.owner_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public void setOwnerUid(Long ownerUid) {
        this.ownerUid = ownerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user_relation.other_uid
     *
     * @return the value of kugga_user_relation.other_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public Long getOtherUid() {
        return otherUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user_relation.other_uid
     *
     * @param otherUid the value for kugga_user_relation.other_uid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public void setOtherUid(Long otherUid) {
        this.otherUid = otherUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user_relation.last_mid
     *
     * @return the value of kugga_user_relation.last_mid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public Long getLastMid() {
        return lastMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user_relation.last_mid
     *
     * @param lastMid the value for kugga_user_relation.last_mid
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public void setLastMid(Long lastMid) {
        this.lastMid = lastMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user_relation.is_pass
     *
     * @return the value of kugga_user_relation.is_pass
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public Byte getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user_relation.is_pass
     *
     * @param pass the value for kugga_user_relation.is_pass
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public void setPass(Byte pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kugga_user_relation.create_time
     *
     * @return the value of kugga_user_relation.create_time
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kugga_user_relation.create_time
     *
     * @param createTime the value for kugga_user_relation.create_time
     *
     * @mbg.generated Fri Jan 31 14:35:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}