package com.ayang818.kugga.services.pojo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public UserRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOwnerUidIsNull() {
            addCriterion("owner_uid is null");
            return (Criteria) this;
        }

        public Criteria andOwnerUidIsNotNull() {
            addCriterion("owner_uid is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerUidEqualTo(Long value) {
            addCriterion("owner_uid =", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidNotEqualTo(Long value) {
            addCriterion("owner_uid <>", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidGreaterThan(Long value) {
            addCriterion("owner_uid >", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_uid >=", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidLessThan(Long value) {
            addCriterion("owner_uid <", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidLessThanOrEqualTo(Long value) {
            addCriterion("owner_uid <=", value, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidIn(List<Long> values) {
            addCriterion("owner_uid in", values, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidNotIn(List<Long> values) {
            addCriterion("owner_uid not in", values, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidBetween(Long value1, Long value2) {
            addCriterion("owner_uid between", value1, value2, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOwnerUidNotBetween(Long value1, Long value2) {
            addCriterion("owner_uid not between", value1, value2, "ownerUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidIsNull() {
            addCriterion("other_uid is null");
            return (Criteria) this;
        }

        public Criteria andOtherUidIsNotNull() {
            addCriterion("other_uid is not null");
            return (Criteria) this;
        }

        public Criteria andOtherUidEqualTo(Long value) {
            addCriterion("other_uid =", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidNotEqualTo(Long value) {
            addCriterion("other_uid <>", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidGreaterThan(Long value) {
            addCriterion("other_uid >", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidGreaterThanOrEqualTo(Long value) {
            addCriterion("other_uid >=", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidLessThan(Long value) {
            addCriterion("other_uid <", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidLessThanOrEqualTo(Long value) {
            addCriterion("other_uid <=", value, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidIn(List<Long> values) {
            addCriterion("other_uid in", values, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidNotIn(List<Long> values) {
            addCriterion("other_uid not in", values, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidBetween(Long value1, Long value2) {
            addCriterion("other_uid between", value1, value2, "otherUid");
            return (Criteria) this;
        }

        public Criteria andOtherUidNotBetween(Long value1, Long value2) {
            addCriterion("other_uid not between", value1, value2, "otherUid");
            return (Criteria) this;
        }

        public Criteria andLastMidIsNull() {
            addCriterion("last_mid is null");
            return (Criteria) this;
        }

        public Criteria andLastMidIsNotNull() {
            addCriterion("last_mid is not null");
            return (Criteria) this;
        }

        public Criteria andLastMidEqualTo(Long value) {
            addCriterion("last_mid =", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidNotEqualTo(Long value) {
            addCriterion("last_mid <>", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidGreaterThan(Long value) {
            addCriterion("last_mid >", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidGreaterThanOrEqualTo(Long value) {
            addCriterion("last_mid >=", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidLessThan(Long value) {
            addCriterion("last_mid <", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidLessThanOrEqualTo(Long value) {
            addCriterion("last_mid <=", value, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidIn(List<Long> values) {
            addCriterion("last_mid in", values, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidNotIn(List<Long> values) {
            addCriterion("last_mid not in", values, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidBetween(Long value1, Long value2) {
            addCriterion("last_mid between", value1, value2, "lastMid");
            return (Criteria) this;
        }

        public Criteria andLastMidNotBetween(Long value1, Long value2) {
            addCriterion("last_mid not between", value1, value2, "lastMid");
            return (Criteria) this;
        }

        public Criteria andPassIsNull() {
            addCriterion("is_pass is null");
            return (Criteria) this;
        }

        public Criteria andPassIsNotNull() {
            addCriterion("is_pass is not null");
            return (Criteria) this;
        }

        public Criteria andPassEqualTo(Byte value) {
            addCriterion("is_pass =", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotEqualTo(Byte value) {
            addCriterion("is_pass <>", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThan(Byte value) {
            addCriterion("is_pass >", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_pass >=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThan(Byte value) {
            addCriterion("is_pass <", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThanOrEqualTo(Byte value) {
            addCriterion("is_pass <=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassIn(List<Byte> values) {
            addCriterion("is_pass in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotIn(List<Byte> values) {
            addCriterion("is_pass not in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassBetween(Byte value1, Byte value2) {
            addCriterion("is_pass between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotBetween(Byte value1, Byte value2) {
            addCriterion("is_pass not between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kugga_user_relation
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 05 13:56:18 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kugga_user_relation
     *
     * @mbg.generated Wed Feb 05 13:56:18 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}