package com.ayang818.kugga.services.mapper;

import com.ayang818.kugga.services.pojo.model.ChatContent;
import com.ayang818.kugga.services.pojo.model.ChatContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChatContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    long countByExample(ChatContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int deleteByExample(ChatContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int insert(ChatContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int insertSelective(ChatContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    List<ChatContent> selectByExampleWithRowbounds(ChatContentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    List<ChatContent> selectByExample(ChatContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    ChatContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChatContent record, @Param("example") ChatContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByExample(@Param("record") ChatContent record, @Param("example") ChatContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByPrimaryKeySelective(ChatContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_content
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByPrimaryKey(ChatContent record);
}