package com.ayang818.kugga.services.mapper;

import com.ayang818.kugga.services.pojo.model.ChatIndex;
import com.ayang818.kugga.services.pojo.model.ChatIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChatIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    long countByExample(ChatIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int deleteByExample(ChatIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int deleteByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int insert(ChatIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int insertSelective(ChatIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    List<ChatIndex> selectByExampleWithRowbounds(ChatIndexExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    List<ChatIndex> selectByExample(ChatIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    ChatIndex selectByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChatIndex record, @Param("example") ChatIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByExample(@Param("record") ChatIndex record, @Param("example") ChatIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByPrimaryKeySelective(ChatIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_message_index
     *
     * @mbg.generated Sun Jan 19 22:08:53 CST 2020
     */
    int updateByPrimaryKey(ChatIndex record);
}