package com.ayang818.kugga.services.mapper;

import com.ayang818.kugga.services.pojo.model.Message;
import com.ayang818.kugga.services.pojo.model.MessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    long countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int deleteByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    List<Message> selectByExampleWithRowbounds(MessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    Message selectByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kugga_message_content
     *
     * @mbg.generated Thu Jan 23 22:35:22 CST 2020
     */
    int updateByPrimaryKey(Message record);
}